
import React from 'react';
import { useDesk } from '../context/DeskContext';
import { useAppWorld } from '../context/AppWorldContext';

const GameplanView: React.FC = () => {
  const { state: { currentSession }, actions: { startGameplan } } = useDesk();
  const { actions: { openRoom } } = useAppWorld();

  if (!currentSession || !currentSession.gameplan) {
      // Start Screen
      return (
          <div className="flex flex-col h-full bg-[#0b0e14] items-center justify-center text-gray-200">
              <div className="w-96 text-center">
                  <h1 className="text-2xl font-bold mb-4">Start New Session</h1>
                  <p className="text-gray-400 mb-8">Let the Desk Coordinator build a gameplan based on your recent performance, current tilt state, and active policies.</p>
                  
                  <div className="grid grid-cols-2 gap-4">
                      <button 
                        onClick={() => startGameplan("London")}
                        className="p-4 bg-[#161a25] border border-gray-700 hover:border-blue-500 rounded-lg transition-all text-sm font-bold"
                      >
                          🇬🇧 London Open
                      </button>
                      <button 
                        onClick={() => startGameplan("NY")}
                        className="p-4 bg-[#161a25] border border-gray-700 hover:border-blue-500 rounded-lg transition-all text-sm font-bold"
                      >
                          🇺🇸 NY Open
                      </button>
                  </div>
              </div>
          </div>
      );
  }

  const gp = currentSession.gameplan;

  return (
    <div className="flex flex-col h-full bg-[#0b0e14] text-gray-200 p-8 overflow-y-auto">
        <div className="max-w-3xl mx-auto w-full">
            <div className="flex justify-between items-end mb-6 border-b border-gray-800 pb-4">
                <div>
                    <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                        {gp.marketSession} Session Gameplan
                        <span className="text-xs bg-blue-900/30 text-blue-300 px-2 py-1 rounded border border-blue-800/50">{currentSession.date}</span>
                    </h1>
                    <p className="text-gray-400 mt-1">Generated by Desk Coordinator</p>
                </div>
                <button 
                    onClick={() => openRoom('tradingRoomFloor')}
                    className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded shadow-lg shadow-emerald-900/20"
                >
                    Accept & Go to Desk
                </button>
            </div>

            {/* Goal Card */}
            <div className="bg-[#131722] border border-gray-700 rounded-lg p-6 mb-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wide mb-2">Primary Objective</h3>
                <div className="text-xl font-medium text-white">{gp.highLevelGoal}</div>
                <div className="mt-4 p-3 bg-red-900/10 border border-red-900/30 rounded text-red-200 text-sm flex items-center gap-2">
                    <span>⛔ Lockdown Trigger:</span>
                    <span className="font-bold">{gp.lockdownTriggerR}R Daily Loss</span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Active Lineup */}
                <div className="bg-[#161a25] border border-gray-800 rounded-lg p-5">
                    <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wide mb-4">Active Playbooks</h3>
                    <div className="space-y-3">
                        {gp.activePlaybooks.length === 0 && <span className="text-gray-500 italic">No playbooks assigned.</span>}
                        {gp.activePlaybooks.map((pb, i) => (
                            <div key={i} className="flex justify-between items-center p-3 bg-black/20 rounded border border-gray-700">
                                <div>
                                    <div className="font-bold text-white">{pb.name}</div>
                                    <div className="text-xs text-gray-500 uppercase">{pb.role}</div>
                                </div>
                                <div className="text-xs font-mono text-blue-300 bg-blue-900/20 px-2 py-1 rounded">
                                    Cap: {pb.riskCapR}R
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Focus Notes */}
                <div className="bg-[#161a25] border border-gray-800 rounded-lg p-5">
                    <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wide mb-4">Focus Notes</h3>
                    <div className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap">
                        {gp.focusNotes}
                    </div>
                </div>
            </div>
        </div>
    </div>
  );
};

export default GameplanView;
