
const { gemini, GEMINI_AUTOPILOT_MODEL, GEMINI_THINKING_CONFIG } = require("../geminiClient");
const { evaluateProposedTrade } = require("../risk/riskEngine");
const playbookPerformanceService = require("./playbookPerformanceService");

/**
 * Generates a structured trade plan using Gemini.
 */
async function generateAutopilotPlan({
  symbol,
  timeframe,
  mode,
  question,
  brokerSnapshot,
  visionSummary,
  riskProfile,
  notes
}) {
  const systemInstruction = `
You are the lead strategist of an AI trading squad.
Your job:
- Read the account snapshot, risk context, **VISION SNAPSHOTS**, and question.
- Propose ONE structured trade plan as JSON.
- Respect strict risk: never exceed requested risk% or blow daily drawdown.
- **IMPORTANT**: You must assign a "playbook" name to this trade (e.g. "NY Liquidity Sweep", "Trend Pullback").
  This will be used to check historical performance stats.

Context:
- Symbol: ${symbol}
- Timeframe: ${timeframe}
- Mode: ${mode}
- Risk Profile: ${riskProfile || "balanced"}
- **VISION CONTEXT**: ${visionSummary || "No vision data available. Rely on price structure implied by question."}
- Extra Notes: ${notes || "none"}

Account:
- Equity: ${brokerSnapshot?.equity || 0}
- Daily PnL: ${brokerSnapshot?.dailyPnl ?? "n/a"}
- Open Positions: ${brokerSnapshot?.openPositionsCount ?? 0}

User Question/Directive: "${question || "Generate a plan if a setup exists."}"

You MUST respond in this exact JSON structure:
{
  "summary": string,
  "rationale": string,
  "riskNotes": string,
  "jsonTradePlan": {
    "direction": "LONG" | "SHORT",
    "symbol": string,
    "entryType": "market" | "limit",
    "entryPrice": number | null,
    "stopLoss": number | null,
    "takeProfits": [{ "level": number, "sizePct": number }],
    "riskPct": number,
    "playbook": string  // REQUIRED: Name of the setup
  },
  "checklist": string[],
  "warnings": string[]
}
`;

  try {
    const response = await gemini.models.generateContent({
      model: GEMINI_AUTOPILOT_MODEL,
      contents: [{ role: "user", parts: [{ text: systemInstruction }] }],
      config: {
        responseMimeType: "application/json",
        ...GEMINI_THINKING_CONFIG
      },
    });

    const text = response.text;
    const parsed = JSON.parse(text);
    return parsed;
  } catch (error) {
    console.error("[AutopilotOrchestrator] Generation failed:", error);
    throw new Error("Failed to generate autopilot plan");
  }
}

/**
 * Runs the plan through the Risk Engine AND checks Playbook Performance.
 */
async function reviewAutopilotPlan(plan, sessionState) {
  const tradePlan = plan.jsonTradePlan;
  
  if (!tradePlan || !tradePlan.direction || !tradePlan.riskPct) {
    return {
      allowed: false,
      reasons: ["Invalid plan structure generated by AI."],
      warnings: [],
      plan
    };
  }

  // 1. Basic Risk Engine Check
  const proposedTrade = {
    direction: tradePlan.direction.toLowerCase(), // 'long' | 'short'
    riskPercent: tradePlan.riskPct,
    comment: plan.summary
  };

  const riskResult = evaluateProposedTrade(sessionState, proposedTrade);
  const reasons = [...riskResult.reasons];
  const warnings = [...riskResult.warnings];
  let allowed = riskResult.allowed;

  // 2. Playbook Performance Check
  let playbookProfile = null;
  if (tradePlan.playbook && tradePlan.symbol) {
     playbookProfile = await playbookPerformanceService.getProfileForPlaybook(tradePlan.playbook, tradePlan.symbol);
     
     if (playbookProfile) {
        if (playbookProfile.health === 'red') {
           allowed = false; // Block RED strategies automatically
           reasons.push(`Playbook '${tradePlan.playbook}' is marked RED (Health Check Failed).`);
           reasons.push(`Stats: Win ${Math.round(playbookProfile.winRate*100)}%, Avg ${playbookProfile.avgR.toFixed(2)}R.`);
        } else if (playbookProfile.health === 'amber') {
           warnings.push(`Playbook '${tradePlan.playbook}' is AMBER. Proceed with caution.`);
           // Optional: Cap risk for amber
           if (tradePlan.riskPct > 0.25) {
              warnings.push("Risk capped to 0.25% due to Amber health status.");
              // In a real implementation, we'd mutate the plan riskPct here
           }
        }
     } else {
        warnings.push(`New or unknown playbook '${tradePlan.playbook}'. No historical data.`);
     }
  }

  return {
    allowed,
    reasons,
    warnings,
    plan,
    riskDetails: riskResult,
    playbookProfile // Pass back to UI
  };
}

module.exports = {
  generateAutopilotPlan,
  reviewAutopilotPlan
};
