
const { gemini, GEMINI_AUTOPILOT_MODEL, GEMINI_THINKING_CONFIG } = require("../geminiClient");
const { evaluateProposedTrade } = require("../risk/riskEngine");

/**
 * Generates a structured trade plan using Gemini.
 * @param {object} params
 * @param {string} params.symbol
 * @param {string} params.timeframe
 * @param {string} params.mode
 * @param {string} [params.question]
 * @param {object} params.brokerSnapshot
 * @param {string} [params.visionSummary]
 * @param {string} [params.riskProfile]
 * @param {string} [params.notes]
 */
async function generateAutopilotPlan({
  symbol,
  timeframe,
  mode,
  question,
  brokerSnapshot,
  visionSummary,
  riskProfile,
  notes
}) {
  const systemInstruction = `
You are the lead strategist of an AI trading squad.
Your job:
- Read the account snapshot, risk context, and question.
- Propose ONE structured trade plan as JSON.
- Respect strict risk: never exceed requested risk% or blow daily drawdown.

Context:
- Symbol: ${symbol}
- Timeframe: ${timeframe}
- Mode: ${mode}
- Risk Profile: ${riskProfile || "balanced"}
- Vision Summary: ${visionSummary || "none"}
- Extra Notes: ${notes || "none"}

Account:
- Equity: ${brokerSnapshot?.equity || 0}
- Daily PnL: ${brokerSnapshot?.dailyPnl ?? "n/a"}
- Open Positions: ${brokerSnapshot?.openPositionsCount ?? 0}

User Question/Directive: "${question || "Generate a plan if a setup exists."}"

You MUST respond in this exact JSON structure:
{
  "summary": string,
  "rationale": string,
  "riskNotes": string,
  "jsonTradePlan": {
    "direction": "LONG" | "SHORT",
    "symbol": string,
    "entryType": "market" | "limit",
    "entryPrice": number | null,
    "stopLoss": number | null,
    "takeProfits": [{ "level": number, "sizePct": number }],
    "riskPct": number
  },
  "checklist": string[],
  "warnings": string[]
}
`;

  try {
    const response = await gemini.models.generateContent({
      model: GEMINI_AUTOPILOT_MODEL,
      contents: [{ role: "user", parts: [{ text: systemInstruction }] }],
      config: {
        responseMimeType: "application/json",
        ...GEMINI_THINKING_CONFIG
      },
    });

    const text = response.text;
    const parsed = JSON.parse(text);
    return parsed;
  } catch (error) {
    console.error("[AutopilotOrchestrator] Generation failed:", error);
    throw new Error("Failed to generate autopilot plan");
  }
}

/**
 * Runs the plan through the Risk Engine.
 * @param {object} plan - The JSON output from generateAutopilotPlan
 * @param {object} sessionState - Minimal session state for risk engine
 */
function reviewAutopilotPlan(plan, sessionState) {
  const tradePlan = plan.jsonTradePlan;
  
  if (!tradePlan || !tradePlan.direction || !tradePlan.riskPct) {
    return {
      allowed: false,
      reasons: ["Invalid plan structure generated by AI."],
      warnings: [],
      plan
    };
  }

  const proposedTrade = {
    direction: tradePlan.direction.toLowerCase(), // 'long' | 'short'
    riskPercent: tradePlan.riskPct,
    comment: plan.summary
  };

  const riskResult = evaluateProposedTrade(sessionState, proposedTrade);

  return {
    allowed: riskResult.allowed,
    reasons: riskResult.reasons,
    warnings: riskResult.warnings,
    plan,
    riskDetails: riskResult
  };
}

module.exports = {
  generateAutopilotPlan,
  reviewAutopilotPlan
};
